version: '3.9'
services:

  deploy:
    build:
      context: ./ConsultasVisuales
    restart: always
    ports:
      - '127.0.0.1:4000:80'
    container_name: angular-app
    networks:
      - mynetwork

  spring-boot-app:
    build:
      context: ./consultas-bigQuery-gcp
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-db  #172.18.0.3:3306  # Asegúrate de proporcionar el nombre del servicio de MySQL aquí
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_PORT: 3306
    networks:
      - mynetwork

  mysql-db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: consult_bd
      #MYSQL_USER: root
      #MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
