
  PROJECT_ID: project-bigquery-404801
  server:
    port: ${DEFAULT_PORT:8080}
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/consult_bd?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 12345678
      #Para Docker
      #url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/consult_bd?useSSL=false&allowPublicKeyRetrieval=true
      #username: ${MYSQL_USER}
      #password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
    application:
      name: app-bigquery
    cloud:
      config:
        namespace: default
        enabled: true
        name: Cloud
        profile: dev, cloud, bigquery
        label: master
      gcp:
        project-id: ${PROJECT_ID:project-bigquery-404801}
        credentials:
          location: classpath:project-bigquery-404801-cecbe05a26bc.json
        bigquery:
          datasetName: ${DATASET_NAME:bigquery-public-data}

  #set up properties